# PROJECT CONFIGURATION FILE

# TIMEFRAME FOR DATA GENERATION
START_DATE = "2022-01-01"
END_DATE = "2024-12-31"

# DATASET SIZES
N_CUSTOMERS = 10
N_PLANS = 9 

# RANDOM SEED
SEED = 44

# EMAIL DOMAIN
DOMAIN = "dataflowiq.com"